### ISSUE TITLE
An error occurred [Errno 2] No such file or directory: 'liked_posts.txt'

### ISSUE THREAD

**Issue by nonokh** [dzaytsev91/mygf-instagram#1]
i am getting this error after running : python example.py

my system: (_uname -a_):
Linux nono-Inspiron-3542 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dzaytsev91** [comment]
@nonokh Thank you for your issue, It is a bug. I pushed the fix, can you pull new version and check if it's working?

**Comment by nonokh** [comment]
WORKED!! thanks ,looking forward for the other plans!
does the bot like new posts or all the posts that i havent liked yet?
also is it possible to add something like retrieving MY  notifications : who  has liked my posts/who has commented/ without having to login.

**Comment by dzaytsev91** [comment]
@nonokh 
Thanks for your issue!
API returns only 9 recent posts, so the bot like only recent posts that you haven't liked.
Unfortunately current unofficial API doesn't provide possibility to get information if you liked post or not without login.
If the problem was fixed I move this issue to resolved.
